version: '3.9'

services:
  app:
    image: "oven/bun"
    entrypoint: []
    command: "/bin/sh -c 'bun install && bun run --watch src/index.ts'"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:12345678@localhost:5432/db?schema=public"
    volumes:
      - "./:/home/bun/app"

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345678